---
- name: OpenShift App Deploy (pre -> apply -> post)
  hosts: local
  gather_facts: no

  vars:
    manifest_dir: "{{ manifest_dir | default('build/manifests') }}"

  tasks:
    - name: Include pre-deploy tasks (migrations, config checks, etc.)
    - import_tasks: ../roles/app_deploy/tasks/pre.yml

    - name: Apply manifests with oc (preferred) or fallback to k8s module
      block:
        - name: Apply using oc if available
          ansible.builtin.shell: |
            set -euo pipefail
            if command -v oc >/dev/null 2>&1; then
              oc apply -f "{{ manifest_dir }}"
            else
              echo "oc not found; using k8s module"
              exit 1
            fi
          register: oc_apply
          changed_when: "'configured' in oc_apply.stdout or 'created' in oc_apply.stdout"
          failed_when: false

        - name: Fallback to k8s module when oc is not present
          when: oc_apply.rc != 0
          kubernetes.core.k8s:
            state: present
            src: "{{ item }}"
          loop: "{{ lookup('ansible.builtin.fileglob', manifest_dir + '/*.y*ml', wantlist=True) }}"
      tags: ['apply']

    - name: Include post-deploy tasks (smoke tests, route health, etc.)
    - import_tasks: ../roles/app_deploy/tasks/post.yml
